### ISSUE TITLE
Multiple threading version to calculate feature matrix

### ISSUE THREAD

**Issue by dfayzur** [Featuretools/featuretools#101]
Hello, 

calculating feature matrix takes reasonable amount of time on single thread, while most of the other threads are doing nothing.

Is it possible to calculate feature matrix in parallel mode with multi threading support?

**Comment by bschreck** [comment]
Hi @dfayzur, we are currently working on a multicore version in PR #84. It should be merged in in the next few weeks, hopefully sooner. In the meantime, users have had success using [Dask bags](https://dask.pydata.org/en/latest/bag.html) to parallelize `calculate_feature_matrix`. See our conversation with @jeff-hernandez on the [Featuretools Gitter](https://gitter.im/featuretools/featuretools).

**Comment by dfayzur** [comment]
Thanks @bschreck. I will look to the Gitter.

**Comment by Seth-Rothschild** [comment]
Closing via #173
