### ISSUE TITLE
featuretools for time series data? 

### ISSUE THREAD

**Issue by unnir** [Featuretools/featuretools#105]
Hi all,

I was wondering, is it make sense to use featuretools for time series data? 

For example:

```
        Time,                             DayOfWeek, Target
0	2014-01-01 01:41:50	1                   0
1	2014-01-01 02:06:50	2                   0
2	2014-01-01 02:31:50	3                   0
3	2014-01-01 02:56:50	4                   0
4	2014-01-01 03:21:50	5                   1
```

**Comment by Seth-Rothschild** [comment]
Hi @unnir,

It's definitely makes sense to use Featuretools for timeseries data! Here's example code to get you started.
```
data = pd.DataFrame({'Time': ['2014-01-01 01:41:50',
                            '2014-01-01 02:06:50',
                            '2014-01-01 02:31:50',
                            '2014-01-01 02:56:50',
                            '2014-01-01 03:21:50'],
                    'Target': [0, 0, 0, 0, 1]})        
data['index'] = data.index
es = ft.EntitySet('My EntitySet')
es.entity_from_dataframe(entity_id='main_data_table',
                         index='index',
                         dataframe=data,
                         time_index='Time')

from featuretools.primitives import Minute, Hour, Day, Month, Year, Weekday
fm, features = ft.dfs(entityset=es, 
                      target_entity='main_data_table', 
                      trans_primitives=[Minute, Hour, Day, Month, Year, Weekday])
```
If there were more data associated with this, it would be important to get [cutoff_times](https://docs.featuretools.com/automated_feature_engineering/handling_time.html) set up before calling DFS. That would ensure that only valid data (as organized by time!) is being used to generate features. 

I'm going to close this issue for now. If you have more questions about getting set up feel free to continue to ask on [gitter](https://gitter.im/featuretools/featuretools).

**Comment by unnir** [comment]
Wow, thank you for your answer!
