### ISSUE TITLE
why calculate this features?

### ISSUE THREAD

**Issue by JYLFamily** [Featuretools/featuretools#178]
Hi featuretools team:

Why featuretools calculate below features?
Like std(SK_ID_PREV)

ft.Relationship(
    self.__es["previous_application"]["SK_ID_PREV"],
    self.__es["installments_payments"]["SK_ID_PREV"]
)  

Thanks

**Comment by kmax12** [comment]
@JYLFamily can you provide more detail in your question so we can better answer it? We recommend sharing the dataset and code you are working with for us to best provide help. Additionally, please post this question on StackOverflow with the Featuretools tag (https://stackoverflow.com/questions/tagged/featuretools). That way we can organize answers for everyone to access. 

I'm going to close this issue, but happy to provide an answer once you post on StackOverflow.
