### ISSUE TITLE
Update conda package

### ISSUE THREAD

**Issue by Ingvar-Y** [Featuretools/featuretools#179]
### Bug/Feature Request Description
Featuretools package on featuretools conda channel still isn't up to v0.2.0, could you kindly update it?

Package for Windows would be a nice bonus.

**Comment by Ingvar-Y** [comment]
I see that release v0.2.2 is already available on conda and it is available for all systems. I guess I can close this issue now. Thanks!

**Comment by Seth-Rothschild** [comment]
Thanks @Ingvar-Y! Let us know if you run into any unexpected issues using the Windows version.
