### ISSUE TITLE
time_index error

### ISSUE THREAD

**Issue by Al2a2d2m** [Featuretools/featuretools#186]
### Bug/Feature Request Description
i used the same dataset on the release and i get no problem. 
I also checked my data more than one time. 
date format : 2017-03-11

``ValueError                                Traceback (most recent call last)
pandas/_libs/tslib.pyx in pandas._libs.tslib.array_to_datetime (pandas\_libs\tslib.c:44294)()

pandas/_libs/src/datetime.pxd in datetime._string_to_dts (pandas\_libs\tslib.c:97369)()

ValueError: Month out of range in datetime string "49"

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
pandas/_libs/tslib.pyx in pandas._libs.tslib.array_to_datetime (pandas\_libs\tslib.c:44703)()

pandas/_libs/tslib.pyx in pandas._libs.tslib.parse_datetime_string (pandas\_libs\tslib.c:34965)()

ValueError: Given date string not likely a datetime.

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-54-ed45adc3d026> in <module>()
      5                               dataframe=data,
      6                               index="IDs",
----> 7                               time_index="DT_DPEC"
      8                               )
      9 

C:\ProgramData\Anaconda3\lib\site-packages\featuretools\entityset\entityset.py in entity_from_dataframe(self, entity_id, dataframe, index, variable_types, make_index, time_index, secondary_time_index, encoding, already_sorted)
    738                                            variable_types=variable_types,
    739                                            encoding=encoding,
--> 740                                            already_sorted=already_sorted)
    741 
    742     def normalize_entity(self, base_entity_id, new_entity_id, index,

C:\ProgramData\Anaconda3\lib\site-packages\featuretools\entityset\entityset.py in _import_from_dataframe(self, entity_id, dataframe, index, variable_types, make_index, time_index, secondary_time_index, last_time_index, parse_date_cols, encoding, already_sorted)
   1294                         relationships=current_relationships,
   1295                         already_sorted=already_sorted,
-> 1296                         created_index=created_index)
   1297         self.entity_dict[entity.id] = entity
   1298         return self

C:\ProgramData\Anaconda3\lib\site-packages\featuretools\entityset\entity.py in __init__(self, id, df, entityset, variable_types, index, time_index, secondary_time_index, last_time_index, encoding, relationships, already_sorted, created_index, verbose)
    114 
    115         # do one last conversion of data once we've inferred
--> 116         self.convert_all_variable_data(inferred_variable_types)
    117 
    118         # todo check the logic of this. can index not be in variable types?

C:\ProgramData\Anaconda3\lib\site-packages\featuretools\entityset\entity.py in convert_all_variable_data(self, variable_types)
    306             if issubclass(desired_type, vtypes.Datetime) and \
    307                     current_type not in _datetime_types:
--> 308                 self.convert_variable_data(var_id, desired_type, **type_args)
    309 
    310     def convert_variable_data(self, column_id, new_type, **kwargs):

C:\ProgramData\Anaconda3\lib\site-packages\featuretools\entityset\entity.py in convert_variable_data(self, column_id, new_type, **kwargs)
    329             # TODO: if float convert to int?
    330             df[column_id] = pd.to_datetime(df[column_id], format=format,
--> 331                                            infer_datetime_format=True)
    332         elif new_type == vtypes.Boolean:
    333             map_dict = {kwargs.get("true_val", True): True,

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\tools\datetimes.py in to_datetime(arg, errors, dayfirst, yearfirst, utc, box, format, exact, unit, infer_datetime_format, origin)
    507     elif isinstance(arg, ABCSeries):
    508         from pandas import Series
--> 509         values = _convert_listlike(arg._values, False, format)
    510         result = Series(values, index=arg.index, name=arg.name)
    511     elif isinstance(arg, (ABCDataFrame, MutableMapping)):

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\tools\datetimes.py in _convert_listlike(arg, box, format, name, tz)
    433                     dayfirst=dayfirst,
    434                     yearfirst=yearfirst,
--> 435                     require_iso8601=require_iso8601
    436                 )
    437 

pandas/_libs/tslib.pyx in pandas._libs.tslib.array_to_datetime (pandas\_libs\tslib.c:46617)()

pandas/_libs/tslib.pyx in pandas._libs.tslib.array_to_datetime (pandas\_libs\tslib.c:46321)()

pandas/_libs/tslib.pyx in pandas._libs.tslib.array_to_datetime (pandas\_libs\tslib.c:44803)()

TypeError: invalid string coercion to datetime

**Comment by kmax12** [comment]
@Al2a2d2m can you make sure your entire `DT_DPEC` column is a pandas datetime type before loading it in to Featuretools? if you need to, you can run 

```
import pandas as pd
df['DT_DPEC'] = pd.to_datetime(df['DT_DPEC'])
```

Let me know if this works.

**Comment by Al2a2d2m** [comment]
thank you kmax12, I already did that and I get the same problem. It's kind of related to the size of the dataframe:
with small dataframe (2 columns) its ok no error,  with bigger one (100 columns in my case i get this error)
i appreciate your help kmax12 thx again .

**Comment by kmax12** [comment]
@Al2a2d2m can you share the file you are trying to load?

**Comment by Al2a2d2m** [comment]
@kmax12 I can't sorry (it contains  personnal data): 
+ its 300MB file with 100 columns, 2 date columns and roughly a million rows. mainly of float type (prices)

**Comment by Al2a2d2m** [comment]
Ok I figured it out. When I create the entity set, FT tries automatically to convert some field to date (columns of zipcodes) i dont know why.(error : ValueError: Month out of range in datetime string "49" see below).  The error disapperar when i force the type of that particular field to categorical using variable_types=...
Every seem to be ok with 100 columns.
Really sorry for this and thank you again @kmax12 .

**Comment by kmax12** [comment]
glad you were able to figure it out. closing this for now
