### ISSUE TITLE
Variable types not respected when normalizing entities

### ISSUE THREAD

**Issue by WillKoehrsen** [Featuretools/featuretools#199]
When trying to normalize an entity, I specify `additional_variables` along with variable types for these variables in the `normalize_entity` call. However, the variable types are not respected. They keep the same type as the type in the base entity.

This example is using the retail data:

```
csv_s3 = "s3://featurelabs-static/online-retail-logs.csv"
data = pd.read_csv(csv_s3, parse_dates=["order_date"])

es = ft.EntitySet(id="Online Retail Logs")

# Add the entire data table as an entity
es.entity_from_dataframe("purchases",
                         dataframe=data,
                         index="purchases_index",
                         time_index = 'order_date')
```
The `description` column is initially categorical:

`description (dtype: categorical)`

However, when I normalize the products entity, I want to change the data type to `Text`. 

```
# create a new "products" entity
es.normalize_entity(new_entity_id="products",
                    base_entity_id="purchases",
                    index="product_id",
                    additional_variables=["description"],
                    variable_types = {'description': ft.variable_types.Text})
```

The `description` column remains a `categorical` despite the specified type. 

```
Entity: products
  Variables:
    product_id (dtype: index)
    description (dtype: categorical)
    first_purchases_time (dtype: datetime_time_index)
  Shape:
    (Rows: 3612, Columns: 3)
```

Is the only way to set a variable type when creating the base entity (using `entity_from_dataframe`)? Setting the variable type when creating the base does work in this case.

**Comment by Seth-Rothschild** [comment]
@kmax12 @WillKoehrsen I think the only place you wouldn't be sure are the `Categorical`/`Index` column of the new entity, which gets handled automatically when you run `normalize_entity` anyways.

Basically I guess the argument comes down to if we want users determining semantic types as they build new entities, or all at once when they load in the data. Personally I prefer doing the latter, but I can see an argument for doing it entity by entity. Is there another way to set variable types directly once the entity has been created?

**Comment by kmax12** [comment]
I am in agreement that a user should do it all at once when they load in data.

There are ways to change the variable types after creating an entity, but we don't advertise it in the public API or encourage using.

**Comment by WillKoehrsen** [comment]
It's hard to think of a non-contrived example where I'd want to change the variable types after creating the base entity. Maybe it would be best to not have the `variable_types` argument in `normalize_entity`. 

Another issue I've noticed is that you can assign to a variable type but nothing changes in the Entity Set. For example:

`es['products']['description'].variable_type = ft.variable_types.Text` 

does not throw an error, but it also doesn't change the variable type. If the most straightforward way to change a variable type is to re-create the Entity Set, then the above code should raise an error so users are not under the impression that they changed the variable type.
