### ISSUE TITLE
Remove convert_links_to_integers from featuretools

### ISSUE THREAD

**Issue by kmax12** [Featuretools/featuretools#218]
Now that we support categorical dtypes within featuretools, this option to normalize entity is unnecessary

**Comment by Seth-Rothschild** [comment]
The change impacts the tests in [test_last_time_index](https://github.com/Featuretools/featuretools/blob/master/featuretools/tests/entityset_tests/test_last_time_index.py#L18). In particular, [test_parent](https://github.com/Featuretools/featuretools/blob/master/featuretools/tests/entityset_tests/test_last_time_index.py#L98) and the test afterwards fail. Investigating now.

**Comment by Seth-Rothschild** [comment]
closing via #219
