### ISSUE TITLE
ft.calculate_feature_matrix takes a long time

### ISSUE THREAD

**Issue by ian-perry-ironnet** [Featuretools/featuretools#230]
### Bug/Feature Request Description
I'm currently using featuretools to transform raw data I have into a format that can be used with scikit learn models.  For the training portion this works great, but when it's time to transform single data points to get predictions, the process seems too slow for the amount of data it's actually operating on.  Specifically ft.calculate_feature_matrix takes about a full second for every data point.  The entity set it's operating on consists of one main entity with ~50 columns and only the one row.  The rest of the 16 entities vary in the number of rows they have but each only has two columns, one being the id that maps the relationship to the main entity and the other being the actual data we're interested in for that entity.  In many cases all 16 of these additional entities only have one row though.  As for the feature set that we're passing to ft.calculate_feature_matrix, it consists of the original 50 columns and 42 new columns created from DFS, however, we have a few categorical variables with a large number of unique values, bringing the final feature count to ~550.

Although this is a large number of features in the end, so many of them are just one-hot-encoded columns.  Plus the base data is so small.  So I'm not sure if this is a
- bug
- strange use-case for featuretools
- or something I'm doing wrong

**Comment by kmax12** [comment]
@ian-perry-ironnet thanks for the details here. is it possible to send the data and code you're working with and we can help you debug more directly? 

if it is a private dataset, you can send an email to help@featuretools.com with that we discuss how to do it securely.

**Comment by kmax12** [comment]
@ian-perry-ironnet did the latest release resolve any of these issues? if not, can you get in touch with us by email or message me directly on gitter (https://gitter.im/featuretools/featuretools) so we can help?
