### ISSUE TITLE
Please publish `featuretools` into conda-forge

### ISSUE THREAD

**Issue by Tagar** [Featuretools/featuretools#241]
### Feature Request Description

Please create conda-forge `featuretools` package, so conda users can seemlessly install Featuretools into conda environments. 

See https://github.com/ContinuumIO/anaconda-issues/issues/10030#event-1826365544 for details. 

Thank you.

**Comment by Tagar** [comment]
Apparently featuretools is available on its own channel, so we can close this ticket.
(would be nice this to be added to conda-forge or anaconda channels though so it's easier to find)

I wasn't able to install featuretools through conda anyway, here's new issue: https://github.com/Featuretools/featuretools/issues/246

Thank you.

**Comment by Seth-Rothschild** [comment]
As in your other issue (#246), it's currently possible to install via conda with `conda install -c featuretools featuretools`. 

We're still considering adding the package to conda forge, but it's low priority since there is another provided option.

**Comment by Seth-Rothschild** [comment]
Moving discussion to #247
