### ISSUE TITLE
Clarify docs on 'Setting a Last Time Index'

### ISSUE THREAD

**Issue by kodonnell** [Featuretools/featuretools#242]
Specifically [here](https://docs.featuretools.com/automated_feature_engineering/handling_time.html#setting-a-last-time-index):

> For example, a customer’s session has multiple transactions which can happen at different points in time. If we are trying to count the number of sessions a user had in a given time period, we often want to count all sessions that had any transaction during the training window. To accomplish this, we need to not only know when a session starts, but when it ends.

Why do we need the session times at all? Can't I just say the below (pseudocode)?

```
select
    count(distinct session_id)
from transactions
where
    customer_id = 123
    and transaction_time between <window_start> and <window_end>
```

I.e. just "count all sessions that had any transaction during the training window". 

Maybe, what's meant to be conveyed is that, say I have a transaction at 1pm and 4pm, but my window is 2pm - 3pm - in this case my above query won't work as there weren't any transactions, despite the session still being 'active' (though that's an interesting assumption). Anyway, if this is what's meant to be conveyed, could we clarify the documentation, as it's unclear and specifically says it isn't this i.e. '_we often want to count all sessions that had any transaction during the training window_'? I find specific examples (such as the above) are great for conveying what's happening.

**Comment by Seth-Rothschild** [comment]
The line
> we often want to count all sessions that had any transaction during the training window.

from the documentation is not technically correct, so we'll update that. What we actually do is that we find if the `last_time_index` is after the start of the training window and the `time_index` is before the cutoff time. That's substantially harder to parse for users, but I can see how the simplification would be misleading. It seems reasonable to change the phrasing to talk about an "active" session.

Note that you can still count transactions under this paradigm with `COUNT(transactions)` which will give exactly the number of transactions within the training window. You can also create a seed feature which counts sessions with no transactions as follows:

```
# context given in the other section
no_transactions = Count(es['transactions']['transaction_id'], es['sessions']) == 0
session_no_transactions = Count(es['sessions']['session_id'], es['customers'], where=no_transactions)
```
Let's move docs discussion to #243 which can handle the necessary change among other issues.


### Code example
In this example we build five rows 5 minutes apart for customer `2`:

```
import pandas as pd
import featuretools as ft
from featuretools.primitives import Count

cutoff_times = pd.DataFrame({"customer_id": [2, 2, 2, 2, 2],
                            "time": pd.date_range('2014-01-01 00:00', periods=5, freq='5min')})

no_transactions = Count(es['transactions']['transaction_id'], es['sessions']) == 0
session_no_transactions = Count(es['sessions']['session_id'], es['customers'], where=no_transactions)

es = ft.demo.load_mock_customer(return_entityset=True)
fm, _ = ft.dfs(entityset=es, 
               target_entity='customers',
               agg_primitives=['count'],
               trans_primitives=[],
               seed_features=[session_no_transactions], 
               cutoff_time=cutoff_times, training_window='30s')
fm
```

The resulting matrix is
```
 COUNT(sessions)   COUNT(transactions)   COUNT(sessions WHERE COUNT(transactions) = 0)
   1.0               1.0                   0.0
   1.0               0.0                   1.0
   1.0               1.0                   0.0
   1.0               0.0                   1.0
   0.0               0.0                   0.0
```
You can see that the session stays open through the first four events but there is no transaction in the training window for the second and fourth events.
