### ISSUE TITLE
What do these parameters mean?

### ISSUE THREAD

**Issue by iWangLin** [Featuretools/featuretools#269]
`features, feature_names = ft.dfs(entityset = es, target_entity = 'tri', 
                                 agg_primitives = ['mean', 'max', 'percent_true', 'last'],
                                 trans_primitives = ['subtract', 'divide'],
                                max_depth =2)`
Where can I find the meaning of these parameters? such as  agg_primitives,   trans_primitives ,or all of dfs

**Comment by kmax12** [comment]
@iWangLin you can find this information in our [documentation](http://docs.featuretools.com). For `dfs` in particular, look [here](https://docs.featuretools.com/generated/featuretools.dfs.html#featuretools.dfs).
