### ISSUE TITLE
Provide better error message when no index is provided and index cannot be inferred 

### ISSUE THREAD

**Issue by kmax12** [Featuretools/featuretools#274]
Currently, `index` is not a required parameter to `EntitySet.entity_from_dataframe` because if no index is provide we will attempt to infer it based on the dataframe. 

However, if we cannot infer and there is no index provided, the user receives the cryptic error message seen in #273.

We should update featuretools to provide a better error message to the user.

**Comment by louis-red** [comment]
Regarding design, it is not clear to me why specifying an index is necessary for the purpose of feature engineering. And if so, wouldn't it be the task of featuretools to add it, and deal with it, in the background ?

**Comment by kmax12** [comment]
There are a couple reason we have the index variable type

1.  `Index` variables are the input type to the `Count` agg primitive and `CumCount` transform primitive. In order to treat those primitive that same as others, Featuretools does need to know which column is the index. To make our design simpler, we don't want to treat index as a "special" column, just a different variable type. 

2.  Often times the dataframe supplied by a user has an index in it. Featuretools needs to know which column is the index in order to avoid calculating invalid features for that column. For example, say your index is a numeric data type, we don't want to calculate the `mean` of that column ever. 

So, as things stand, Featuretools is designed around having an index column in the dataframe. Featuretools does try to help the user when an index doesn't exist. However, we only go as far as creating the column for you, but we require the user supplies the name of the column.

An alternative solution would be to autogenerate the name for the user. However, we feel requiring the user to provide an name helps us avoid errors. In particular, the case where there is a column in the dataframe that is the index, but the user forgot to supply that information to us. By requiring the name, we force users to explicitly consider if there is an index column already in their data. 

We're open to reconsidering this design, but this is our rational at the moment.

**Comment by louis-red** [comment]
Bug not present anymore in the latest master. Maybe I will PR a test to this entity creation.

**Comment by kmax12** [comment]
This is likely resolved in #336 where we update the error messages for initializing entities. Feel free to comment if you think it could be done better and we will reopen
