### ISSUE TITLE
Provide more helpful error message when cutoff time rows are duplicated

### ISSUE THREAD

**Issue by WillKoehrsen** [Featuretools/featuretools#275]
Currently, the error produced when a `cutoff_time` dataframe has duplicate rows and is used in `ft.dfs` is 

`Exception: cannot handle a non-unique multi-index!`

This is not very helpful and it can be frustrating trying to figure out the real issue. 

A better error message would highlight the problem:

`Exception: cutoff time dataframe has duplicate rows.`

**Comment by WillKoehrsen** [comment]
I think providing a helpful error message is better than internally dropping duplicates in `cutoff_time` because the user should probably investigate why the rows are duplicated.

**Comment by kmax12** [comment]
Fixed in #276  closing
