### ISSUE TITLE
support for non-relational data? 

### ISSUE THREAD

**Issue by ZhensongQian** [Featuretools/featuretools#28]
Great to see this "Deep Feature Synthesis" tool to help automate the feature engineering. 
Based on the paper "Deep feature synthesis: Towards automating data science endeavors"-
DSAA2015, and online DOC (https://docs.featuretools.com/index.html), currently it seems like DFS could only support "relation data" (couple entity tables and relational tables)?
Do I miss something? 
Any plan to include the support for non-relational data (e.g. only one big table) as well?

**Comment by kmax12** [comment]
Yes, you can run on featuretools on one big table.

Many of the primitives we support do not require relationships to be defined. If you read about [primitives](https://docs.featuretools.com/automated_feature_engineering/primitives.html) in our documentation you can read about these "transform" primitives, as well as learn how to define your own custom primitives. Custom primitves can be used to extend featuretools to unstructured data types like images and text. 

If you have an example dataset you're working with, I'd be happy to help you figure out how to apply featuretools to it. My email is in my github profile.

**Comment by kmax12** [comment]
Closing this issue for now. Please email help@featuretools.com if you have any other questions.

**Comment by ZhensongQian** [comment]
@kmax12  Thanks for the reply. Great to hear the confirmation. I will look into the details for the `transform` primitives.
