### ISSUE TITLE
Make id an optional parameter to EntitySet constructor

### ISSUE THREAD

**Issue by kmax12** [Featuretools/featuretools#294]
Currently, users must provide an `id` to initialize an `EntitySet`.

```
import featuretools as ft
ft.EntitySet(id="my_entity_set")
```

This is only used by the `repr` of the EntitySet, so we shouldn't require users to provide it. For most users, this is the first line of Feautretools code they write, so we shouldn't have arguments that aren't necessary.  

To fix this issue we should 

1. make `id` an optional argument to the `EntitySet` constructor 
2. allow methods of entityset that use the id to function without a provided id
3. Edit examples in the Index and "Representing Data with EntitySets" of the documentation to not require using an `id`. 
4. make sure we have a test case when `id` isn't provided

**Comment by ew4321** [comment]
I'll work on it tonight

**Comment by kmax12** [comment]
fixed by #324
