### ISSUE TITLE
Multithread feature name creation issue on macOS

### ISSUE THREAD

**Issue by ugurcanlacin** [Featuretools/featuretools#314]
### Bug/Feature Request Description
I try to create only feature names in parallel, but it only works with 1 thread. Here is what I tried so far.
I read the documentation [here](https://docs.featuretools.com/guides/parallel.html#using-persistent-cluster). Then, I tried LocalCluster. I always monitor **_htop_** results.

```
from dask.distributed import Client, LocalCluster
cluster = LocalCluster()
feature_names = ft.dfs(entityset = es, target_entity = 'financial-records',
                       trans_primitives = trans_primitives,
                       max_depth = 2, verbose = 0,
                       dask_kwargs={'cluster': cluster},
                       features_only=True)
```

After running this code, there was only one thread running 100% for this process.

Then, I changed dask_kwargs as follows:

`                       dask_kwargs={'cluster': cluster.scheduler.address}`

Nothing changed. Then, I tried to remove dask_kwargs and add n_jobs as follows:

```
feature_names = ft.dfs(entityset = es, target_entity = 'financial-records',
                       trans_primitives = trans_primitives,
                       max_depth = 2, verbose = 0,
                       n_jobs=6,
                       features_only=True)
```

Nothing changed again. I am not able to run this feature creation in parallel. 

Before starting my own implementation, I tried your example code. I am able to run [this notebook](https://github.com/Featuretools/Automated-Manual-Comparison/blob/master/Loan%20Repayment/notebooks/Featuretools%20on%20Dask.ipynb) in parallel. But it is feature matrix calculation.

Could you show me some way to go?

**Comment by kmax12** [comment]
@ugurcanlacin only feature calculation will run in parallel, not the feature generation. so this is expected behavior when `features_only=True`. 

we should clarify this in the documentation. thanks for posting!

**Comment by kmax12** [comment]
we haven't seen feature generation be a bottleneck in most cases. that being said, there are probably opportunities to improve the existing code before thinking about how to parallelize deep feature synthesis. we could do it if there was a enough demand though.
