### ISSUE TITLE
Add details about serialization features to the documentation

### ISSUE THREAD

**Issue by kmax12** [Featuretools/featuretools#315]
Features saved in one version of Featuretools may not be able to be loaded in another version of Featuretools. 

We should add this to the documentation for `ft.save_features` and `ft.load_features` as well as the [deployment](https://docs.featuretools.com/guides/deployment.html) page.

**Comment by WillKoehrsen** [comment]
I opened a pull request  #316 to address this. It updates the `save_features` and `load_features` functions docstrings as well as the deployment page. Is there anywhere else we should alert users to this behavior?

**Comment by WillKoehrsen** [comment]
Closed by #316. This provides documentation alerting the user to behavior but does not address the stability issue.
