### ISSUE TITLE
Plotting EntitySets

### ISSUE THREAD

**Issue by floscha** [Featuretools/featuretools#381]
Hey everyone,

I thought it would be great if it was possible to plot a visual representation of an *EntitySet*, like one can for example [plot the structure of a neural network in Keras](https://www.tensorflow.org/api_docs/python/tf/keras/utils/plot_model):

```python
es = ft.demo.load_mock_customer(return_entityset=True)
es.plot()
```

So I build some quick prototype which looks like the following:

![screeshot](https://user-images.githubusercontent.com/33159547/51755945-16cf3a00-20c0-11e9-8ce5-104a4e7431d6.png)

If you think that such a method could add value to the **featuretools** library, then I'll happily create a proper pull request for this.

**Comment by kmax12** [comment]
That is a great idea and something that has been requested by users. A PR would be great.

**Comment by bukosabino** [comment]
I have some problems with graphviz when I use es.plot().

At first, I get this error:

`ImportError: Please install graphviz to plot entity sets. (See https://pypi.org/project/graphviz/ for details)`

It is resolved with `pip install graphviz`. So, we need to add this package to requirements.txt. But, then I get:

`ExecutableNotFound: failed to execute ['dot', '-Tsvg'], make sure the Graphviz executables are on your systems' PATH`

I have tried using conda:

`conda install python-graphviz`

But, it's not fixed on my Mac. Let me know if you have any hint.

**Comment by bukosabino** [comment]
Ok. So, to use `es.plot()` people need to install graphviz as backend:

Mac OS:
`brew install graphviz`

Linux (Ubuntu example):
`sudo apt-get install graphviz`

Windows:
`conda install python-graphviz`

Now, we need to add the graphviz package on requirements.txt too.

**Comment by kmax12** [comment]
@bukosabino because graphviz can be a bit challenging to install on different platforms, we made it an optional requirement for people who want to use it. your comment on this issue is good documentation for it and we can add more to the docs after we get some feedback on people's experience installing it.

**Comment by kmax12** [comment]
closing since #382 has been merged in and released in featuretools v0.6.0

**Comment by rwedge** [comment]
The plotting tests require graphviz, so we should probably add graphviz to the test requirements or flag them as optional in some way.

**Comment by kmax12** [comment]
ah, yes let's do that. can you open a PR?
