### ISSUE TITLE
CumCount, CumMax, CumMean, CumMin and CumSum no longer supported as transform primitive

### ISSUE THREAD

**Issue by ericchansen** [Featuretools/featuretools#405]
### Bug/Feature Request Description

As of commit 36ce3c300172390d702a614b5784332b8b56343a, CumCount, CumMax, CumMean, CumMin and CumSum can't be used as transform primitives.

This breaks the demo at https://github.com/Featuretools/Automated-Manual-Comparison/blob/master/Retail%20Spending/notebooks/Automated%20Retail%20Spending.ipynb.

**Comment by kmax12** [comment]
thanks for pointing that out. 

we will be adding these primitives back into the next release.
