### ISSUE TITLE
trans_primitives "IsWeekend"

### ISSUE THREAD

**Issue by rathorology** [Featuretools/featuretools#413]
### Bug/Feature Request Description
Method "IsWeekend" in trans_primitives throws error.
change "IsWeekend" to "is_weekend" solves the issue.

**Comment by ayushpatidar** [comment]
thanks, @rathorology for raising the issue and providing the solution I was facing this error from past two days

**Comment by kmax12** [comment]
thank you. so we can fix this, where did you see code that had the wrong string for "is_weekend"? @rathorology @ayushpatidar

**Comment by rathorology** [comment]
Documentation

**Comment by kmax12** [comment]
where in the documentation? 

The confusion might be that there are two ways to use the primitive. You use a string like this 

```
feature_defs = ft.dfs(target_entity="sessions",
                      entityset=es, 
                      trans_primitives=["is_weekend"])
```

Or, pass the object like this

```
from featuretools.primitives import IsWeekend
feature_defs = ft.dfs(target_entity="sessions",
                      entityset=es, 
                      trans_primitives=[IsWeekend])
```

**Comment by rathorology** [comment]
Got it, thanks.
