### ISSUE TITLE
Does anything constrain the variable type class definitions?

### ISSUE THREAD

**Issue by jxwolstenholme** [Featuretools/featuretools#427]
### Bug/Feature Request Description
Hi,

As per https://github.com/Featuretools/featuretools/issues/290 I'm just having a look at the variable types and in particular the ZIPCode one.

When it says that that 5 or 9 digit zipcodes are supported, is anything checking this?

https://github.com/Featuretools/featuretools/blob/d93ff0ddd39a4d8c7881e59577e61feabc033790/featuretools/variable_types/variable.py#L235-L241

As I can't find any reference to it, I'm assuming not but could be wrong. 

For this reason, is it fine to just create new classes in this style? For example if I wanted to add an [ISO-3166](https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes) country code would it look like this? : - 

```
class ISO3166(Categorical):
"""Represents an ISO-3166 Country Code.
Consists of an Alpha 2 or Alpha 3 code which is 
cast as a string.
"""
    _dtype_repr = "iso3166"
    _default_pandas_dtype = str 
```

Thanks

**Comment by kmax12** [comment]
@jxwolstenholme Yep, you can create new classes in that style.

In the future, we may introduce a more robust API that does validation based on variable type, but for right now, the code you put if fine. 

Let us know if you have any other questions!

**Comment by kmax12** [comment]
we are also open to contributions of general purpose variable types. if you are interested, you can put up a PR for a `CountryCode` variable type to featuretools.
