### ISSUE TITLE
Add PhoneNumber, DateOfBirth, URL variable types

### ISSUE THREAD

**Issue by gsheni** [Featuretools/featuretools#443]
### Add PhoneNumber, DateOfBirth, URL variable types
-----
- Add PhoneNumber Variable Type
- Add DateOfBirth Variable Type 
- Add URL Variable Type
- Add these types to ` featuretools/tests/testing_utils/mock_ds.py`
- Add to `docs/source/api_reference.rst`
- **Two PR Examples of adding new Variable Types #430 and #426**
```python
class PhoneNumber(Variable):
    _dtype_repr = "phone_number"
    _default_pandas_dtype = str

class DateOfBirth(Datetime):
    _dtype_repr = "date_of_birth"
    _default_pandas_dtype = np.datetime64

class URL(Variable):
    _dtype_repr = "url"
    _default_pandas_dtype = str
```

**Comment by glentennis** [comment]
@gsheni , some small questions:

- how strict is the phone number format? what will we allow? do we want country code?
- same question for urls. is the url any valid url? or should there be an "http://" at the front?

**Comment by gsheni** [comment]
- We should allow any common number format.
- the url is any valid url.
