### ISSUE TITLE
utils.load_data   error

### ISSUE THREAD

**Issue by AWalkInClouds** [Featuretools/featuretools#464]
<img width="1403" alt="屏幕快照 2019-03-18 下午2 36 30" src="https://user-images.githubusercontent.com/35360577/54511244-52cd9f80-498b-11e9-9b03-5ba30e1680f5.png"> utils .  not install?

**Comment by kmax12** [comment]
`utils` isn't a featuretools core library package. are you getting this from one of the demos?

**Comment by AWalkInClouds** [comment]
Problem solved. Utils.py is not in the directory. Thank you.
