### ISSUE TITLE
Improve error message when target entity doesn't exist in your entityset

### ISSUE THREAD

**Issue by kmax12** [Featuretools/featuretools#466]
We should catch the error of the target entity not existing in the entityset and give a more informative warning. 

We can also improve the error message seen in #465. It should say "KeyError: 'Entity order_date does not exist in entity set'" when the entity doesn't exist since the id may be none

**Comment by NirantK** [comment]
This would be a lot more informative. Happy to take this up over the weekend once I make enough progress on #465.
