### ISSUE TITLE
featuretools installation problem

### ISSUE THREAD

**Issue by VJSo007** [Featuretools/featuretools#478]
I use windows and I am facing the following problem when I try and install featuretools

Collecting featuretools
  Using cached https://files.pythonhosted.org/packages/78/2a/8cee22677c82c6ecdaa6ffb320ea4384bfeb859ad620319684793b313326/featuretools-0.7.0-py3-none-any.whl
Collecting psutil>=5.4.8 (from featuretools)
  Using cached https://files.pythonhosted.org/packages/16/6a/cc5ba8d7e3ada0d4621d493dbdcb43ed38f3549642916a14c9e070add21a/psutil-5.6.1-cp36-cp36m-win_amd64.whl
Requirement already satisfied: numpy>=1.13.3 in c:\users\vjred\anaconda3\lib\site-packages (from featuretools) (1.15.4)
Requirement already satisfied: toolz>=0.8.2 in c:\users\vjred\anaconda3\lib\site-packages (from featuretools) (0.8.2)
Requirement already satisfied: pyyaml>=3.12 in c:\users\vjred\anaconda3\lib\site-packages (from featuretools) (3.12)
Collecting distributed>=1.24.2 (from featuretools)
  Using cached https://files.pythonhosted.org/packages/a0/83/c1ce8abc42efc520c23a0575c3d191438f74cb710cda98b4a55490244ece/distributed-1.26.1-py2.py3-none-any.whl
Collecting click>=7.0.0 (from featuretools)
  Using cached https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl
Requirement already satisfied: scikit-learn>=0.20.0 in c:\users\vjred\anaconda3\lib\site-packages (from featuretools) (0.20.2)
Requirement already satisfied: tqdm>=4.19.2 in c:\users\vjred\anaconda3\lib\site-packages (from featuretools) (4.28.1)
Collecting cloudpickle>=0.4.0 (from featuretools)
  Using cached https://files.pythonhosted.org/packages/6e/bc/67f13115adcce4efc5e4d7f8220fb9a50aaa2b5c7ed460b26cbb76aa76ad/cloudpickle-0.8.1-py2.py3-none-any.whl
Collecting dask>=1.1.0 (from featuretools)
  Using cached https://files.pythonhosted.org/packages/0e/c3/dc200eac6927d99b2ba7746ac173b238d56fef7c89d811b5e842560def90/dask-1.1.5-py2.py3-none-any.whl
Requirement already satisfied: pandas>=0.23.0 in c:\users\vjred\anaconda3\lib\site-packages (from featuretools) (0.24.1)
Requirement already satisfied: future>=0.16.0 in c:\users\vjred\anaconda3\lib\site-packages (from featuretools) (0.17.1)
Collecting msgpack (from distributed>=1.24.2->featuretools)
  Using cached https://files.pythonhosted.org/packages/8b/fa/975afb5122b563729b93d99b321e3323dee32cdb20b581b5e231d2b49161/msgpack-0.6.1-cp36-cp36m-win_amd64.whl
Requirement already satisfied: six in c:\users\vjred\anaconda3\lib\site-packages (from distributed>=1.24.2->featuretools) (1.10.0)
Collecting tblib (from distributed>=1.24.2->featuretools)
  Using cached https://files.pythonhosted.org/packages/4a/82/1b9fba6e93629a8557f9784cd8f1ae063c8762c26446367a6764edd328ce/tblib-1.3.2-py2.py3-none-any.whl
Collecting sortedcontainers!=2.0.0,!=2.0.1 (from distributed>=1.24.2->featuretools)
  Using cached https://files.pythonhosted.org/packages/13/f3/cf85f7c3a2dbd1a515d51e1f1676d971abe41bba6f4ab5443240d9a78e5b/sortedcontainers-2.1.0-py2.py3-none-any.whl
Collecting tornado>=5 (from distributed>=1.24.2->featuretools)
  Using cached https://files.pythonhosted.org/packages/9d/76/8a52c49e0a7e2638442f379d34f55232c773d4df7f69b297e451c980f99d/tornado-6.0.2-cp36-cp36m-win_amd64.whl
Collecting zict>=0.1.3 (from distributed>=1.24.2->featuretools)
  Using cached https://files.pythonhosted.org/packages/bd/45/a2e6f95a850cd407d785f2f8624b02e72baf6ab910aea4bdcac7e18b4871/zict-0.1.4-py2.py3-none-any.whl
Requirement already satisfied: scipy>=0.13.3 in c:\users\vjred\anaconda3\lib\site-packages (from scikit-learn>=0.20.0->featuretools) (0.18.1)
Requirement already satisfied: python-dateutil>=2.5.0 in c:\users\vjred\anaconda3\lib\site-packages (from pandas>=0.23.0->featuretools) (2.6.0)
Requirement already satisfied: pytz>=2011k in c:\users\vjred\anaconda3\lib\site-packages (from pandas>=0.23.0->featuretools) (2016.10)
Requirement already satisfied: heapdict in c:\users\vjred\anaconda3\lib\site-packages (from zict>=0.1.3->distributed>=1.24.2->featuretools) (1.0.0)
Installing collected packages: psutil, cloudpickle, msgpack, click, tblib, sortedcontainers, tornado, zict, dask, distributed, featuretools
  Found existing installation: psutil 5.0.1
Cannot uninstall 'psutil'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

can someone guide me for this.
many thanks.

**Comment by rwedge** [comment]
Hi @VJSo007, another user encountered this issue (#197) and was able to resolve it by creating a [virtual python environment](https://virtualenv.pypa.io/en/latest/) and installing featuretools in a new environment.

**Comment by VJSo007** [comment]
I was able to solve this problem using conda install featuretools after restarting my laptop several times.

I am closing this issue. Thank you.
