### ISSUE TITLE
different top_n(encode_features) values for multiple features

### ISSUE THREAD

**Issue by wujunzhuo** [Featuretools/featuretools#505]
In the `encode_features` function, the parameter `top_n` controls the number of the feature categories. 

However, it's unlikely to set different values on different categorical features (e.g. `top_n = {'Feature: color': 8, 'Feature: shape': 5}`). Is there a good way to achieve that?

**Comment by kmax12** [comment]
You're right that this is not currently possible with the API. 

You could potentially do it by making multiple calls to `encode_features` with just a subset of your feature matrix and feature definitions. Then you could combine those results. 

We'd be open to a proposal for an API for this problem and then a PR that implemented this once we all agreed. 

Thanks!
