### ISSUE TITLE
pyspark dataframe

### ISSUE THREAD

**Issue by quancore** [Featuretools/featuretools#518]
I could not find any clue how to integrate featurtools to pyspark data frames. For all examples, pandas data frames have been used even if spark example which is strange. Can you provide a guide for spark data frames?

**Comment by kmax12** [comment]
We recommend [this article](https://blog.featurelabs.com/featuretools-on-spark-2/) on our blog which explains how to do it with the open source library. 

Featuretools Enterprise also has this functionality built in. You can read more in the docs [here](https://docs.featurelabs.com/documentation/spark).
