### ISSUE TITLE
Don't pin versions in requirements.txt

### ISSUE THREAD

**Issue by PaulHobbs** [Featuretools/featuretools#52]
Per https://packaging.python.org/discussions/install-requires-vs-requirements/#install-requires,

featuretools is breaking convention by pinning specific versions of all its dependencies in install-requires: _"It is not considered best practice to use install_requires to pin dependencies to specific versions"_

Specifically, this is causing a dependency conflict when I try to install the following packages with pipenv:

pipenv --python 2.7
pipenv install numpy scipy pandas scikit-learn tensorflow featuretools

**Comment by kmax12** [comment]
Thanks for pointing this out. Let me look into the versions we can allow for each of the dependencies and update this as soon as possible.

**Comment by kmax12** [comment]
@PaulHobbs I just put up #53. However, I still need to look into the minimum versions we can support. Can you share which packages / version you were having conflicts with? That would help as starting point for me to test. Thanks!

**Comment by PaulHobbs** [comment]
Hey Max,

Sorry I’m on my phone at the moment, but the conflict was between pandas
0.23.something and pandas 0.22.something (which featuretools requires). You
should be able to reproduce it by installing the latest version of
virtualenv and pipenv and running the commands I listed.

**Comment by davidas85** [comment]
having the same issue - the main conflict is that i want to use pandas 0.21.* and featuretools is forcing 0.20.3.
It also uninstalled my existing cloudpickle (downgraded version from 0.5.2) and future (upgraded from 0.15.2).

**Comment by kmax12** [comment]
@davidas85 thanks for the additional info. I have a PR #53 unpinning the requirements if you want to instal it directly. For some reason, tests are failing on Python 3.4, but pass on 2.7, 3.5, and 3.6.

**Comment by kmax12** [comment]
fixed by #53 and #64
