### ISSUE TITLE
Improve error message when make_time_index is invalid

### ISSUE THREAD

**Issue by CJStadler** [Featuretools/featuretools#537]
For `normalize_entity` function, the argument `make_time_index` is could be a string or a boolean.

There are two cases where `make_time_index` might not be valid (if its a string):
* Specifying an existing column for `make_time_index` but not adding that column to `additional_variables` or `copy_variables`.
* Setting `make_time_index` to a column that doesn't exist in the base frame.

See https://github.com/Featuretools/featuretools/pull/535#discussion_r282472988

**Comment by gsheni** [comment]
The assertion check should be added in the `normalize_entity` function
