### ISSUE TITLE
can featuretools only apply to one-table datasets

### ISSUE THREAD

**Issue by ajoeajoe** [Featuretools/featuretools#582]
can featuretools only apply to one-table datasets(maybe I just can not find related documentation)

**Comment by kmax12** [comment]
Hi there,

Take a look at these two posts

1. https://stackoverflow.com/questions/52418152/featuretools-can-it-be-applied-on-a-single-table-to-generate-features-even-when
2. https://stackoverflow.com/questions/50145953/how-to-apply-deep-feature-synthesis-to-a-single-table

Please let us know if it helps!

**Comment by ajoeajoe** [comment]
Many Thanks, I think you should give some example for different specific dataset or problems(time series), which is tsfresh or Tensorflow do, indeed, Featuretools is a very good tool.

**Comment by ajoeajoe** [comment]
Many Thanks, I think we will appreciate that if you guys can give more demo examples regarding to different specific datasets or problems(e.g. time series), which is tsfresh or Tensorflow do, indeed, Featuretools is a very good tool.
