### ISSUE TITLE
Error when calling "load_features": 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

### ISSUE THREAD

**Issue by nutle** [Featuretools/featuretools#596]
When trying to call 

```saved_features = ft.load_features(feature_definitions)``` 

the following error is returned:

```
Error in py_call_impl(callable, dots$args, dots$keywords) :
  UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

Detailed traceback:
  File "<string>", line 19, in create_variables
  File "/usr/local/lib/python3.6/site-packages/featuretools/feature_base/features_deserializer.py", line 52, in load_features
    return FeaturesDeserializer.load(filepath).to_list()
  File "/usr/local/lib/python3.6/site-packages/featuretools/feature_base/features_deserializer.py", line 76, in load
    features_dict = json.load(f)
  File "/usr/lib64/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
  File "/usr/lib64/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
```

This works without problems on local machine, where the features are developed, but the problem arises when trying to deploy the load on a docker VM. 

What could the problem be? 

Notes: featuretools version is 0.8.0 for centos, python 3.6 - while on the developers machine the package version is the same, but on python 3.7 - could this cause the problem?

**Comment by kmax12** [comment]
@nutle python versions could be the problem. are you able to provide a reproducible example?

**Comment by nutle** [comment]
So far a workaround is generating the features in the same environment as loading them. Not very convenient, but works.

I've noticed though, that on python 3.6 machine the "feature_definitions" object is at least 10 times  larger in size: while "feature_definitions" file, generated on python3.7 machine takes, i.e., 170KB, the same output using the same code and input on python3.6 results in a file of 2100KB. Further, the larger file seems to have a clean json structure, while the smaller seems to be compiled or zipped. This probably explains the observed behaviour.

**Comment by kmax12** [comment]
are you sure you have featuretools 0.8.0 installed in python 3.6?

**Comment by nutle** [comment]
Yes, double checked this, and it says 0.8.0 in the generated json too
________________________________

**Comment by kmax12** [comment]
sorry, I mean 0.8.0 in python 3.7. they should both be clean json files

**Comment by nutle** [comment]
I hope this is it, will check. Thanks!
________________________________

**Comment by nutle** [comment]
Indeed, the dev machine had 0.7.1 featuretools. Sorry for such a silly issue! 

On the other hand, a backward compatibility between the methods would be nice for cases like these, but anyway thanks for keeping up the great work!

**Comment by kmax12** [comment]
in fact, that's exactly why we moved to the JSON format in 0.8.0. Much more backwards compatible then using pickle.
