### ISSUE TITLE
CumCount doesn't get applied

### ISSUE THREAD

**Issue by kmax12** [Featuretools/featuretools#607]
The way we match inputs breaks in `ft.dfs` for `groupby_trans_primitives` breaks when one of the inputs to primitive is an `Id` variable like is the case in `CumCount`.

The issue is with how we append `Id` on this line when looking for matching inputs.

Here is an example the reproduces the issue

```import featuretools as ft

es = ft.demo.load_mock_customer(return_entityset=True)

fl = ft.dfs(target_entity="sessions",
       entityset=es,
       agg_primitives=[],
       trans_primitives=[],
       groupby_trans_primitives=["cum_count"],
       features_only=True)
fl
```

produces 

```
[<Feature: customer_id>, <Feature: device>, <Feature: customers.zip_code>]
```

which is missing `<Feature: CUM_COUNT(sessions) by customer_id>`

**Comment by chaupmcs** [comment]
@kmax12 : I have the same issue.

By the way, I do not really understand the use case of `cum` functions (e.g.,  `cum_sum`, `cum_mean`,...)

All I found in the Internet is this line in the document:

> ft.dfs now has a groupby_trans_primitives parameter that DFS uses to automatically construct features that group by an ID column and then apply a transform primitive to search group. This change applies to the following primitives: CumSum, CumCount, CumMean, CumMin, and CumMax.
Link: https://docs.featuretools.com/changelog.html

I tried to use some `cum` functions in my data, It returns the results (expect the `cum_count`) but I couldn't figure out how they work to create the output.

Can anyone please give me an example to use these functions.

Thanks.

**Comment by kmax12** [comment]
@chaupmcs does [this answer](https://docs.featuretools.com/frequently_asked_questions.html#What-is-the-difference-between-the-primitive-types-(Transform,-GroupBy-Transform,-&-Aggregation)?) in our FAQ help explain? 

also, if you share your code that you're comparing to featuretools, we may be able to identify the discrepancy.

**Comment by xyutech** [comment]
May I ask a question that is not directly connected to the issue. Why there is only customers.zip_code in output? What about join and birth dates? Why they are filtered out?
