### ISSUE TITLE
Getting the internal function from a primitive

### ISSUE THREAD

**Issue by Seth-Rothschild** [Featuretools/featuretools#62]
I've been looking at pulling out the internal function from a primitive. Having access to the function allows for making some very powerful custom primitives:

1. It allows for compositions like `Mean(CumSum(Absolute()))` to be a depth 1 primitive. 
2. It give easy access to changing input and output types of primitives through the `make_x_primitive` API (e.g. make `NumHour` as `Hour` but with a `vtypes.Numeric` output)
3. It allows for mild modifications of existing primitives as new primitives (e.g. return `3*Mean + 1` or `Mean(3*array)+1`).  

The problem is that it seems kind of hard to get at that base function. In python3, I can do
```
from featuretools.primitives import Absolute
abs = Absolute.get_function([]) 
```
which calculates `abs([-1, 0 1])` to be `array([1, 0, 1])`. If we used the `Sum` primitive instead and did 
```
sum = Sum.get_function([])
```
then `sum([-1, 0 1])` would throw an error. The underlying function for sum wants a `pd.Series`, so `sum(pd.Series([-1, 0, 1])` would get the desired result of 0. I haven't managed to find a way to hack together the base function for `Hour` or `CumSum` or in python2 at all.

Would it be worth putting together a `def get_underlying_function` which smooths over these type discrepancies for a user?

**Comment by bschreck** [comment]
The problem you're seeing is that the function is stored inside of an instance method instead of a class method, right? So that in order to access it you need an actual instance of a primitive rather than the primitive class itself. I could see it making sense to have the function stored as an instance function, and then the get_function() method would basically return the function with the "self" variable in scope.

Can you explain a little more what you mean by composing functions into depth 1 primitives?

If I'm understanding correctly, you want to do the following:

`MeanAbsolute = Mean(Absolute)`
And other the hood MeanAbsolute would have the following function:

`np.nanmean(np.absolute(array))`

**Comment by Seth-Rothschild** [comment]
> The problem you're seeing is that the function is stored inside of an instance method instead of a class method, right? So that in order to access it you need an actual instance of a primitive rather than the primitive class itself. 

I think that's right. For custom primitive though, it's not necessarily possible to have a base feature on hand to do `Absolute(base_feature)`

> Can you explain a little more what you mean by composing functions into depth 1 primitives?

Your example here is what I meant by function composition, the key point being that `MeanAbsolute` is a depth 1 primitive instead of being created automatically as a depth 2 one. The user also wouldn't necessarily know that it's `np.absolute` under the hood, just that it's whatever function `Absolute` is using which takes arrays to arrays.

**Comment by bschreck** [comment]
I like the idea of composing primitives like that. Generally you'd pass these primitives as seed_features, where depth is ignored and they are treated just like variables in the entityset. But it could matter if you pass a composed primitive class into the agg_primitives or trans_primitives DFS parameters.

**Comment by Seth-Rothschild** [comment]
The more I think about it the more sold I am.

Not only is a `seed_feature` dataset specific but the function also doesn't get applied later in relevant places, which is a big part of the power of DFS. It also gets us better use from "intermediate primitives" which we've only been using for seed features so far.

For example, in NYC Taxi 4 there's a `GEOBOX` seed feature which finds if a latlong is between two other fixed latlongs (i.e. is this point close to JFK airport). In that demo each `GEOBOX` needed to be individually applied to both the `pickup_latlong` and the `dropoff_latlong` while it's really a trans primitive in disguise.

With access to the underlying function, one could pull out the function from `GEOBOX` and make a new custom primitive to check each interesting range of values.

**Comment by Seth-Rothschild** [comment]
Started #66 to work on this. Added `classmethod` as suggested and that fixes python2 and datetime type problems.

**Comment by kmax12** [comment]
This is an interesting problem, but we need need to think more about the best solution. 

Right now, primitives might use instance attributes to dynamically define the function they return when you call `get_function`. For example, the `NMostCommon` primitive depends on the `n` that the primitive is initialized with. For now, let's keep the current convention and not take the the approach of making get_function a class method.

If we want to solve this, another route forward might be a helper method to automatically compose two primitives, but I suspect we need more usage of custom primitives to best understand the path forward.

**Comment by kmax12** [comment]
This is now possible. For example, this is what it looks like for `Mean` which optionally has a parameter

```
>>> from featuretools.primitives import Mean
>>> mean = Mean()
>>> mean([1, 2, 3, 4, 5, None])
3.0
```

```
>>> mean = Mean(skipna=False)
>>> mean([1, 2, 3, 4, 5, None])
nan
```

Take a look at a any of the documentation for any and we now have examples https://docs.featuretools.com/api_reference.html#feature-primitives
