### ISSUE TITLE
Feature Request: Ability to drop redundant variable in ft.encode_features()

### ISSUE THREAD

**Issue by rohan-gt** [Featuretools/featuretools#635]
Is it possible to add a _drop_first_ parameter to the _ft.encode_features()_ function similar to _pandas.get_dummies()_ ?

**Comment by kmax12** [comment]
Yes, this would be possible. Would you interested in contributing a PR that implements this?

**Comment by ayushpatidar** [comment]
hi @kmax12 
I am interested in contributing for this feature .Can i work on this feature?

**Comment by kmax12** [comment]
@ayushpatidar definitely! if you'd like to discuss/feedback on your implementation feel free to message us on our [Slack](https://join.slack.com/t/featuretools/shared_invite/enQtNTEwODEzOTEwMjg4LTZiZDdkYjZhZTVkMmVmZDIxNWZiNTVjNDQxYmZkMzI5NGRlOTg5YjcwYmJiNWE2YjIzZmFkMjc1NDZkNjBhZTQ)
