### ISSUE TITLE
Defined Custom Primitive does not work

### ISSUE THREAD

**Issue by rohan-gt** [Featuretools/featuretools#636]
I tried to write the following custom primitive to extract the quarter from datetime columns but Featuretools isn't able to detect it:

`class Quarter(TransformPrimitive):`
`"""Determines the quarter of the year from a datetime."""`

    name = "quarter"
    input_types = [Datetime]
    return_type = Ordinal

    def get_function(self):
        def quarter(vals):

            return pd.DatetimeIndex(vals).quarter.values

        return quarter

**Comment by rwedge** [comment]
Hi @rohan-gt, more information might be helpful here.  How were you expecting Featuretools to detect the custom primitive?

I used code similar to that in your example:
```python
import featuretools as ft
import pandas as pd


class Quarter(ft.primitives.TransformPrimitive):
    """Determines the quarter of the year from a datetime."""
    name = "quarter"
    input_types = [ft.variable_types.Datetime]
    return_type = ft.variable_types.Ordinal

    def get_function(self):
        def quarter(vals):
            return pd.DatetimeIndex(vals).quarter.values
        return quarter

es = ft.demo.load_retail()
```

If I then run DFS using the string of the custom class in `trans_primitives`:
```python
fl = ft.dfs(entityset=es,
            target_entity="customers",
            agg_primitives=[],
            trans_primitives=["quarter"],
            features_only=True)
```
I get the following error:

```
ValueError: ('Unknown transform primitive quarter. ', 'Call ft.primitives.list_primitives() to get', ' a list of available primitives')
```

However if I pass the class in directly:
```python
fl = ft.dfs(entityset=es,
            target_entity="customers",
            agg_primitives=[],
            trans_primitives=[Quarter],
            features_only=True)
```
One feature gets created

```
[<Feature: QUARTER(first_orders_time)>]
```

**Comment by rohan-gt** [comment]
Yes that was the issue thanks
