### ISSUE TITLE
Manually remove specific features from feature definitions list

### ISSUE THREAD

**Issue by jonimatix** [Featuretools/featuretools#645]
Hello,

Is it possible to remove a few features from a feature definition list,. after saving a feature definition using: ft.save_features(features, "feature_definitions.json") ?

For example I need to remove 10 specific definitions correctly, without corrupting the json of the file structure?

Is it possible to do so at the moment using specific code or functionality?

Thanks a lot for your help,
Jon

**Comment by gsheni** [comment]
Yes, you can do this.

Let's say you wanted to select features that had the `amount` in its name. You can check for this by using the `get_name` function on the feature definitions.

```python
import featuretools as ft

es = ft.demo.load_mock_customer(return_entityset=True)
feature_matrix, feature_defs = ft.dfs(entityset=es,
                                      target_entity="customers")

features_with_amount = []
for x in feature_defs:
    if 'amount' in x.get_name():
        features_with_amount.append(x)
ft.save_features(features_with_amount, 'feature_definitions.json')
```

**Comment by jonimatix** [comment]
Amazing, thank you so much!
