### ISSUE TITLE
Wrong doctstring

### ISSUE THREAD

**Issue by ayushpatidar** [Featuretools/featuretools#646]
In encode_features() in featuretools. top_n attribute type is declared as pd.dataframe() in docstring. It should be int.
 Args:
            feature_matrix (pd.DataFrame): Dataframe of features.
            features (list[PrimitiveBase]): Feature definitions in feature_matrix.
            top_n (pd.DataFrame): Number of top values to include.
            include_unknown (pd.DataFrame): Add feature encoding an unknown class.
                defaults to True
            to_encode (list[str]): List of feature names to encode.
                features not in this list are unencoded in the output matrix
                defaults to encode all necessary features.
            inplace (bool): Encode feature_matrix in place. Defaults to False.
            verbose (str): Print progress info.

**Comment by kmax12** [comment]
@ayushpatidar thanks for catching. feel free to submit a PR yourself to fix it! otherwise, let us know and we can do it.
