### ISSUE TITLE
Features by Group

### ISSUE THREAD

**Issue by jonimatix** [Featuretools/featuretools#654]
Hello,

Is it possible to let FeatureTools to generate features based on a grouping?

For ex if I have the following data set

DateIndex   ProductID   SalesAmount
13                456                7378
14                456                8990
15                456                9005
12                789                5611
13                789                5353
14                789                1224
15                789                890
12                123                332
13                123                755

Can you group the features by ProductID, sorted by DateIndex?

Thanks a lot for your support.
Jon

**Comment by kmax12** [comment]
hi @jonimatix - you likely want to create new entities in your single table of data. Take a look at the answer to this question on stackoverflow and let us know if it helps!

https://stackoverflow.com/questions/50145953/how-to-apply-deep-feature-synthesis-to-a-single-table

**Comment by jonimatix** [comment]
Hi @kmax12, thanks for the reply, but not sure if the thread resembles the problem I posted. It would be great if you can provide a guided example how I can solve this to ensure that the features created by FT are strictly for the product group?

Thanks a lot

**Comment by kmax12** [comment]
i am not sure if I understand what you mean by "ensure that the features created by FT are strictly for the product group". can you provide an example of what you want the out feature matrix to be?

**Comment by jonimatix** [comment]
Hello @kmax12 ,

Apologies for not being clear enough. I just want to be certain that running FT on the entire data set above, yields the same features as running FT individually on each ProductID (456, 789, and 123) ? Therefore wouldn't need to loop for each ProductID and execute FT for each group?

Thanks for your help

**Comment by kmax12** [comment]
i think that is already what it does. are you observing something different?

**Comment by jonimatix** [comment]
Ok thanks @kmax12  just wanted to confirm it works as mentioned.

Appreciate your help
