### ISSUE TITLE
Specify primitives to apply per column or per entity

### ISSUE THREAD

**Issue by philipus** [Featuretools/featuretools#655]
#### Bug/Feature Request Description

I would like to have optionally an API for DFS to set the trans_primitives or agg_primitives on column level instead of dataframe level because.

Two benefits you gain

1) control the features
2) save resources / run time

#### Expected Input

agg_primitives = {'quantity': [sum, mean], 'category': [last, mode]}

instead of

agg_primitives = ['sum','mean','last','mode']

**Comment by ayushpatidar** [comment]
@kmax12 
if someone is not working on this can i work on this functionality.

**Comment by kmax12** [comment]
@ayushpatidar no one is working on this at the moment. The first step is to finalize API and the behavior. Would you like to put together a proposal?

**Comment by ayushpatidar** [comment]
@kmax12 
sure max.
how should we get started?

**Comment by kmax12** [comment]
I started a shared markdown document [here](https://hackmd.io/s/BkoF8Dq-S). Would you like to start filling out the API and adding other design considerations? 

if you would like to discuss more, please join our [Slack](https://join.slack.com/t/featuretools/shared_invite/enQtNTEwODEzOTEwMjg4LTZiZDdkYjZhZTVkMmVmZDIxNWZiNTVjNDQxYmZkMzI5NGRlOTg5YjcwYmJiNWE2YjIzZmFkMjc1NDZkNjBhZTQ) and message me in the #development channel.
