### ISSUE TITLE
autofunction documentation issues - featuretools.dfs

### ISSUE THREAD

**Issue by alvinthai** [Featuretools/featuretools#67]
Hi,

I noticed that a few parameters (``entities`` and ``ignore_variables``) are missing in the documentation for [featuretools.dfs](https://docs.featuretools.com/generated/featuretools.dfs.html#featuretools.dfs). This is probably due to the input types for these parameters being specified as **dict[str: something]** in the docstring for [featuretools.synthesis.dfs](https://github.com/Featuretools/featuretools/blob/master/featuretools/synthesis/dfs.py).

I would recommend reformatting the input type in the docstring by replacing the colon with another character to fix the documentation issues.

**Comment by kmax12** [comment]
@alvinthai thanks for pointing this out. we'll get it fixed for the next release
