### ISSUE TITLE
calculate_feature_matrix error for tqdm versions < 4.32

### ISSUE THREAD

**Issue by CJStadler** [Featuretools/featuretools#695]
With tqdm 4.31.1
```shell
pytest featuretools/tests/computational_backend/test_calculate_feature_matrix.py::test_dask_kwargs
```

Raises
```
AttributeError: 'tqdm' object has no attribute 'reset'

featuretools/computational_backends/calculate_feature_matrix.py:542: AttributeError
```
https://github.com/Featuretools/featuretools/blob/815c46b5e25c22d8c6ad2f4403df656b8a1ab629/featuretools/computational_backends/calculate_feature_matrix.py#L540-L542

Should we update `requirements.txt` to specify `tqdm>=4.32.0`?

**Comment by kmax12** [comment]
ah, yes. can you put a PR?
