### ISSUE TITLE
ValueError: ('Unknown transform primitive numwords. ',

### ISSUE THREAD

**Issue by xiaodaigh** [Featuretools/featuretools#714]
### Bug/Feature Request Title
ValueError: ('Unknown transform primitive numwords. ',

#### Bug/Feature Request Description

I was just following along this tutorial https://github.com/Featuretools/predict-loan-repayment/blob/master/Automated%20Loan%20Repayment.ipynb

and I was up to this part

```python
# Default primitives from featuretools
default_agg_primitives =  ["sum", "std", "max", "skew", "min", "mean", "count", "percent_true", "num_unique", "mode"]
default_trans_primitives =  ["day", "year", "month", "weekday", "haversine", "numwords", "characters"]

# DFS with specified primitives
feature_names = ft.dfs(entityset = es, target_entity = 'app',
                       trans_primitives = default_trans_primitives,
                       agg_primitives=default_agg_primitives, 
                       where_primitives = [], seed_features = [],
                       max_depth = 2, n_jobs = -1, verbose = 1,
                       features_only=True)
```

and the below error occured. 

#### Expected Output

> 
Built 1575 features

#### Output of ``featuretools.show_info()``

> Traceback (most recent call last):
>   File "C:\git\featuretools-tutorial\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3326, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
>   File "<ipython-input-12-335551234f71>", line 6, in <module>
>     features_only=True)
>   File "C:\git\featuretools-tutorial\venv\lib\site-packages\featuretools\utils\entry_point.py", line 46, in function_wrapper
>     raise e
>   File "C:\git\featuretools-tutorial\venv\lib\site-packages\featuretools\utils\entry_point.py", line 38, in function_wrapper
>     return_value = func(*args, **kwargs)
>   File "C:\git\featuretools-tutorial\venv\lib\site-packages\featuretools\synthesis\dfs.py", line 196, in dfs
>     seed_features=seed_features)
>   File "C:\git\featuretools-tutorial\venv\lib\site-packages\featuretools\synthesis\deep_feature_synthesis.py", line 158, in __init__
>     t = check_trans_primitive(t)
>   File "C:\git\featuretools-tutorial\venv\lib\site-packages\featuretools\synthesis\deep_feature_synthesis.py", line 805, in check_trans_primitive
>     " a list of available primitives")
> ValueError: ('Unknown transform primitive numwords. ', 'Call ft.primitives.list_primitives() to get', ' a list of available primitives')
> 

#### info

> Name: featuretools
> Version: 0.10.1
> Summary: a framework for automated feature engineering
> Home-page: http://featuretools.com
> Author: Feature Labs, Inc.
> Author-email: support@featurelabs.com
> License: BSD 3-clause
> Location: c:\git\featuretools-tutorial\venv\lib\site-packages
> Requires: s3fs, cloudpickle, toolz, pyyaml, pandas, numpy, future, scikit-learn, distributed, smart-open, tqdm, dask, click, psutil
> Required-by:

**Comment by kmax12** [comment]
@xiaodaigh thanks for reporting. does changing it to `num_words` fix the problem?

**Comment by xiaodaigh** [comment]
Yes, it does. But "characters" nor "character" work. Same error:

> ValueError: ('Unknown transform primitive characters. '

**Comment by kmax12** [comment]
@xiaodaigh that should be `num_characters`

**Comment by kmax12** [comment]
we've updated the repo. if anything else comes up, can you post it in that repo specifically? this repo is for Featuretools development

**Comment by Joel-Reji** [comment]
@kmax12 what should i replace with num_characters
