### ISSUE TITLE
Is this timing normal?

### ISSUE THREAD

**Issue by xiaodaigh** [Featuretools/featuretools#715]
### Bug/Feature Request Title
Abnormally long expected run time. The estimate keep climbing! And progress remains 0.

I ran on Windows 10 and featuretools 0.10.1

I was just following along this tutorial https://github.com/Featuretools/predict-loan-repayment/blob/master/Automated%20Loan%20Repayment.ipynb

except I couldn't get this line to run

```python
#default_trans_primitives =  ["day", "year", "month", "weekday", "haversine", "numwords", "characters"]
```
so I dropped two primitives

```python
#default_trans_primitives =  ["day", "year", "month", "weekday", "haversine"]
```

#### Bug/Feature Request Description

I was just following along this tutorial https://github.com/Featuretools/predict-loan-repayment/blob/master/Automated%20Loan%20Repayment.ipynb

#### Expected Output
Within the hour

#### Output of ``featuretools.show_info()``
Elapsed: 19:46 | Progress:   0%|          | Remaining: 899:20:03

**Comment by kmax12** [comment]
Hi,

Can you post this in this in that repo specifically? This repo is for Featuretools development.

Thanks,
Max
