### ISSUE TITLE
Add number of rows to EntitySet.plot()

### ISSUE THREAD

**Issue by kmax12** [Featuretools/featuretools#722]
The repr of an `EntitySet` shows the number of rows. 

```python
import featuretools as ft
es = ft.demo.load_mock_customer(return_entityset=True)
es
```
```
Entityset: transactions
  Entities:
    transactions [Rows: 500, Columns: 5]
    products [Rows: 5, Columns: 2]
    sessions [Rows: 35, Columns: 4]
    customers [Rows: 5, Columns: 4]
  Relationships:
    transactions.product_id -> products.product_id
    transactions.session_id -> sessions.session_id
    sessions.customer_id -> customers.customer_id
```

The `.plot()` method is frequently preferred by users since it shows the same information and more visually, with the exception of the number of rows.

![plot](https://user-images.githubusercontent.com/371792/64134421-cb92ad80-cdab-11e9-9eb4-19b7f2512c21.png)

To improve `.plot()`, we should decide on a way to add the number of rows to the output

**Comment by MarcoGorelli** [comment]
I'd be interested in trying this...one idea could be to just add it in brackets. So where it says `transactions`, it could instead say `transactions (500 rows)`, and similarly for the others
