### ISSUE TITLE
Loading / saving features doesn't support file-like objects as input

### ISSUE THREAD

**Issue by rwedge** [Featuretools/featuretools#73]
Currently Featuretools supports saving a list of features to disk and loading them from disk using a file path as an input.  If these functions supported file-like objects as an alternate input we could save features to string buffers or unnamed temporary files.

**Comment by kmax12** [comment]
this was recently asked about on stackoverflow. I left an potential solution for the S3 case: https://stackoverflow.com/questions/55482233/can-feature-tools-save-feature-list-directly-to-s3/55486555#55486555

**Comment by rwedge** [comment]
To summarize the expected calls:
* Returns the serialized features as a string
```python
ft.save_features(features) 
```
* Saves the serialized features as a file
```python
ft.save_features(features, '/path/to/save/to.txt')
```
* Save the features to open file `f`
```python
ft.save_features(features, f)
```
* Save the features to s3 file
```python
ft.save_features(features, "s3://bucket/file.txt")
```
