### ISSUE TITLE
Tackling lag variables?

### ISSUE THREAD

**Issue by joshvoigts** [Featuretools/featuretools#734]
How does featuretools incorporate lag variables? For example at each row, how could I produce the following if I have two variables `a` and `b`. Also, how can I produce interactions between `a` and lagged `a` or lagged `b` using a training_window.

    index, a, a(n-1), a(n-2), b, b(n-1), b(n-2)

Sample expected output where cumulative primitives apply to the last 5 time steps:

    index, a, IDENTITY(a(n-1)), CUM_MEAN(a), DIFF(a), b, MEAN(a, b), MAX(a, b), etc...

**Comment by kmax12** [comment]
@joshvoigts i see you closed the issue. if you found a way to solve it, we'd definitely appreciate it if you could share. That way others hitting the same issue can see how you approached it. As FT developers, it's also helpful for us to understand how people use the software, so we can improve our documentation to better support future users. Thanks!
