### ISSUE TITLE
Error with 'entity_from_csv'

### ISSUE THREAD

**Issue by ab-anssi** [Featuretools/featuretools#80]
I am trying to extract features automatically with featuretools from [Windows event logs available online](https://csr.lanl.gov/data/cyber1/). When I run `entity_from_csv` on the authentication dataset I get an error like "segmentation fault" or "free: invalid pointer".
 
To reproduce the error :

- [a subset of the authentication dataset](https://drive.google.com/open?id=1gghBnTgTilnkP8pBQUGR2zheLehIicpD)
- [python script](https://github.com/Featuretools/featuretools/files/1676946/error__entity_from_csv.zip)

The csv file contains 13,000,000 lines. When I take only the first 12,000,000 lines there is no error. When I take only the last 1,000,000 there is no error either, so I do not think the problem is due to the content (like a special character) of the last lines.

Do you have an idea about the origin of this error ?

Context :
- installation with pip install featuretools
- run with python 2.7
- 64Go (more than enough for the dataset considered)

**Comment by kmax12** [comment]
@ab-anssi we are planning to remove `entity_from_csv` in the next release. Can you use pandas directly to load into a dataframe and then try `entity_from_dataframe`? This is what `entity_from_csv` does under the hood and hopefully can help us work around or figure out this error. Let us know if this helps.

**Comment by kmax12** [comment]
closing this issue for now. @ab-anssi please create a new issue if you still have problems after this work around.
