### ISSUE TITLE
EntitySet Concat() does not reindex data

### ISSUE THREAD

**Issue by bschreck** [Featuretools/featuretools#83]
EntitySets store an internal dictionary mapping the indexes that connect entities across relationships. This speeds up computation time by enabling quicker joins, much like what a database  does. To create these indexes, inside of `EntitySet.add_relationship`, we internally call:

```
self.index_data(relationship)
```

However, when we concat two EntitySets like this:
```
es_updated = es_old.concat(es_new)
```

We update the internal dataframes of `es_old` but do not update the indexes. This affects `calculate_feature_matrix` down the road not just as a performance hit, but also potentially in the actual feature values.

An easy fix is to add the following to `EntitySet.concat`:
```
for r in es.relationships:
    es.index_data(r)
```

**Comment by kmax12** [comment]
adding @rwedge since he worked on `EntitySet.concat`
