### ISSUE TITLE
pls share written explanation of algorithm

### ISSUE THREAD

**Issue by Sandy4321** [Featuretools/featuretools#88]
in order to use your code correctly , it needs to understand algorithm

**Comment by bschreck** [comment]
Hi @Sandy4321 .

To learn more about Deep Feature Synthesis (the underlying algorithm we use to generate features), check out this [blog post](https://www.featurelabs.com/blog/deep-feature-synthesis/) and this [paper](https://www.featurelabs.com/wp-content/uploads/2017/12/DSAA_DSM_2015-1.pdf).

**Comment by Seth-Rothschild** [comment]
To add to what @bschreck said, you can read more about DFS in the relevant [documentation](https://docs.featuretools.com/automated_feature_engineering/afe.html) page and see some examples of how to use it in on the [demos](https://www.featuretools.com/demos) page. For now, I'm going to close the issue, but you should feel free to ask more questions about installing on windows on [your other issue](#87) or to ask for help on  [gitter](https://gitter.im/featuretools/featuretools).
